### DISCUSSION TITLE
可否把瞬间顶部分类的那个模块设置成可隐藏

### DISCUSSION THREAD

**Discussion by IshuaWang** [hcjike/halo-theme-dream2.0-plus#35] [General]
目前个人主题加了这一块看起来不是很美观，如果可以隐藏掉保留原样就好了

**Comment by mjsoftking** [comment]
标签那部分吗

**Reply by IshuaWang** [reply]
是的

**Comment by mjsoftking** [comment]
@IshuaWang  1.3.3.beta4

**Reply by IshuaWang** [reply]
还有个问题，主题设置了建站时间之后，页脚全显示0，是不是一个bug？
![image](https://github.com/user-attachments/assets/4a7671f8-7850-4a84-b969-a379f53f24e0)

**Reply by mjsoftking** [reply]
> 还有个问题，主题设置了建站时间之后，页脚全显示0，是不是一个bug？

没有遇到过，可以发下站点看看

**Reply by IshuaWang** [reply]
发现了，这里算时分秒直接取余应该不对
![image](https://github.com/user-attachments/assets/79c20dea-4d10-4c7e-b19f-8237fd7a7200)

**Comment by mjsoftking** [comment]
![image](https://github.com/user-attachments/assets/0db9b5d3-a08f-436b-8cf7-28c1d14ead9a)
没有遇到问题

**Reply by IshuaWang** [reply]
你选一个过去的时间看看

**Comment by mjsoftking** [comment]
![image](https://github.com/user-attachments/assets/4a6d8f30-9251-494d-ad42-db3240fdc717)

**Comment by mjsoftking** [comment]
![image](https://github.com/user-attachments/assets/392f9e71-7f55-436c-8e08-ce7650197e8a)

**Reply by IshuaWang** [reply]
我知道了，common.min.js是对的，但是common.js不对，可能我这个用的时common.js，什么情况会这么选啊？

**Reply by IshuaWang** [reply]
我还是没找到问题在哪，你看看我的站点https://blog.wangyx.com/

**Comment by IshuaWang** [comment]
还有，我打开瞬间页面好像会跳出下面两个错误：
![image](https://github.com/user-attachments/assets/9d796d1c-8e18-40a3-91ad-44e5c6867add)
![image](https://github.com/user-attachments/assets/2754eb17-aa30-4892-a8ef-41d60923bb28)
有点奇怪

**Reply by mjsoftking** [reply]
@IshuaWang 
![image](https://github.com/user-attachments/assets/96a82708-e901-4e1f-8d60-77e0be3c2a74)
把这个打开

**Reply by IshuaWang** [reply]
感觉可以优化一下，还有那个时间统计的是怎么回事啊？

**Reply by mjsoftking** [reply]
你先改一下，有可能是bug引起的定时器没启动

这个bug是halo，2.20.11引起的，他的一个改动导致原本记录的默认值没了，修改回来就还需重新配置才行

**Comment by mjsoftking** [comment]
[1.3.3.beta5](https://github.com/zsjy/halo-theme-dream2.0-plus/releases/tag/1.3.3.beta5)

**Comment by mjsoftking** [comment]
[halo-theme-dream2.0文档](https://www.hcjike.com/docs/halo-theme-dream2.0)

**Comment by mjsoftking** [comment]
``` css
<style type="text/css">html {
  --background2: rgba(255, 255, 255, 0.1);
}
html.night {
  --background2: rgba(40, 44, 52, .1);
}
.section .card {
  background: var(--background2);
}
.tag{
  background: var(--background2);
}
.admire .admire-content button {
  color: #000000;
  background: var(--background2) !important;
}
.article-operation .level-item a,
.article-operation .level-item a:before {
  background: var(--background2);
}
.journal .card-tab div,
.journal .card-tab div:before {
  background: var(--background2);
  color: var(--main);
  border-color: var(--background2);
}
.journal .journal-teams .item {
  background: var(--background2);
  color: var(--main);
  border: 1px solid lightgray;
  
  &.active {
      background: rgba(64,224,208,.1);
  }
}
.journal .journal-content{
  background: var(--background2);
}
</style>
```
瞬间标签栏应该是你自己注入的样式导致的
